# Generated by Django 6.0.3 on 2026-05-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_external_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bluesky',
            field=models.CharField(blank=True, help_text='Bluesky handle e.g. you.bsky.social', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle without @', max_length=100),
        ),
        migrations.AlterField(
            model_name='editsuggestion',
            name='target_type',
            field=models.CharField(choices=[('event', 'Event'), ('venue', 'Venue'), ('artist', 'Artist'), ('neighborhood', 'Neighborhood'), ('promoter', 'Crew / Collective / Promoter')], max_length=20),
        ),
    ]
