# Generated by Django 6.0.3 on 2026-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0102_userprofile_social_handles'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterprofile',
            name='last_promoted_at',
            field=models.DateTimeField(blank=True, help_text='Last time profile was blasted to social media', null=True),
        ),
    ]
