# Generated by Django 6.0.3 on 2026-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_promoterprofile_last_promoted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertask',
            name='task_type',
            field=models.CharField(choices=[('geocode_event', 'Geocode Event'), ('geocode_venue', 'Geocode Venue'), ('post_bluesky', 'Post to Bluesky'), ('generate_event_flyer', 'Generate Event Flyer')], db_index=True, max_length=50),
        ),
    ]
