# Generated by Django 6.0.3 on 2026-06-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_alter_venuefeed_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuefeed',
            name='source_type',
            field=models.CharField(choices=[('ical', 'iCal Feed'), ('eventbrite', 'Eventbrite API'), ('musicbrainz', 'MusicBrainz API'), ('squarespace', 'Squarespace Events JSON'), ('19hz', '19hz.info PNW Listing'), ('eael', 'EAEL WordPress Calendar (data-events scrape)'), ('rhp', 'RHP/RootsHouse venue listing (HTML scrape)'), ('localist', 'Localist calendar API (colleges/orgs)')], default='ical', max_length=20),
        ),
    ]
