# Generated by Django 6.0.3 on 2026-05-14 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('bpm_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bpm_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy', models.CharField(blank=True, choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('mood', models.CharField(blank=True, help_text='Comma-separated mood descriptors', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related', models.ManyToManyField(blank=True, help_text='Tokens that share sonic or cultural DNA', to='wiki.genretoken')),
            ],
            options={
                'verbose_name': 'Genre Token',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompoundGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mb_id', models.CharField(blank=True, max_length=40, verbose_name='MusicBrainz ID')),
                ('lastfm_tag', models.CharField(blank=True, max_length=200)),
                ('discogs_style', models.CharField(blank=True, max_length=200)),
                ('beatport_name', models.CharField(blank=True, max_length=200)),
                ('wikipedia_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tokens', models.ManyToManyField(related_name='compound_genres', to='wiki.genretoken')),
            ],
            options={
                'verbose_name': 'Compound Genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TokenAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='wiki.genretoken')),
            ],
            options={
                'verbose_name': 'Token Alias',
                'verbose_name_plural': 'Token Aliases',
                'ordering': ['alias'],
                'unique_together': {('token', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='TokenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('wikipedia', 'Wikipedia'), ('musicbrainz', 'MusicBrainz'), ('lastfm', 'Last.fm'), ('discogs', 'Discogs'), ('listenbrainz', 'ListenBrainz'), ('beatport', 'Beatport'), ('allmusic', 'AllMusic'), ('rateyourmusic', 'RateYourMusic'), ('community', 'Community'), ('editmusic', 'edit.music library')], max_length=20)),
                ('source_name', models.CharField(blank=True, help_text='Name of the entry on the source (may differ from our token name)', max_length=200)),
                ('source_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('confidence', models.CharField(choices=[('verified', 'Verified'), ('consensus', 'Community Consensus'), ('derived', 'Derived from data'), ('proposed', 'Proposed')], default='derived', max_length=20)),
                ('listener_count', models.PositiveIntegerField(blank=True, help_text='Last.fm listeners, Beatport chart position, etc.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wiki.genretoken')),
            ],
            options={
                'verbose_name': 'Token Source',
                'ordering': ['source'],
                'unique_together': {('token', 'source')},
            },
        ),
    ]
