# Generated by Django 6.0.3 on 2026-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundgenre',
            name='track_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks in library with this exact compound (updated by sync)'),
        ),
        migrations.AddField(
            model_name='genretoken',
            name='track_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks in library carrying this token (updated by sync)'),
        ),
    ]
